"""initial schema with ledger

Revision ID: f42c847a586d
Revises: 
Create Date: 2026-01-11 16:21:05.510337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42c847a586d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('bill_discount_type', sa.String(length=10), nullable=True),
    sa.Column('bill_discount_value', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bill_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('item_discount_type', sa.String(length=10), nullable=True),
    sa.Column('item_discount_value', sa.Float(), nullable=True),
    sa.Column('final_item_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_transaction_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name='fk_group_bill'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name='fk_tx_bill'),
    sa.ForeignKeyConstraint(['group_id'], ['bill_transaction_group.id'], name='fk_tx_group'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_transaction')
    op.drop_table('bill_transaction_group')
    op.drop_table('bill_item')
    op.drop_table('item')
    op.drop_table('bill')
    # ### end Alembic commands ###
